### ISSUE TITLE
Supported file and directory structure

### ISSUE THREAD

**Issue by shdotcom** [thiagodnf/analysis#3]
Hi thiagodnf,
would you please provide an example for supported file and directory structure that can be used with analysis tool?
Thank you

**Comment by thiagodnf** [comment]
Hello @shdotcom 

There is a folder called " example". You can look into the structure you are looking for.

The basic structure is: 

> instance_name / algorithm_name / parameter_settings/ FUN files

* FUN files are those one with objective values for each found solution

**Comment by shdotcom** [comment]
Hi thiagodnf,

When I selected open>> example>> instance_a>>algo_a>>setting_a, it does not show any data.
but it works when I pressed on "Generator" button.

Thank you

**Comment by thiagodnf** [comment]
Hi!

I don't remember well now but I guess you have to select the "example" folder when you click on "open" button. The same thing you have to do when push the "generate" button
